import numpy as np

N_DATA_POINTS = 100
TRAINING_DATASET_SEED = 123
# Will determine the number of test datasets
TEST_DATASET_SEEDS = 1234 + np.arange(10)

N_COLLINEAR = 4
N_NONCOLLINEAR = 4

STD_COLLINEAR = 1.0
STD_NONCOLLINEAR = 1.0
NOISE_COLLINEAR = 0.4
COEFF_COLLINEAR = 0.1
COEFF_NONCOLLINEAR = 1.0
PHI = 0.1
COEFF_INTERCEPT = 1.0

EDUCABILITY = 0.30
FORGETTING = 0.00

COST_VAR = 0.05
COST_EDU = 0.5

N_INTERACTIONS = 20

THETA_1 = 1.0
THETA_2 = 1.0

HEURISTIC_N_SAMPLES = 10
TERMINAL_COST_ERR_MLT = 5
USER_SWITCH_SIM_A = 1.0
